### ISSUE TITLE
it show me this error

### ISSUE THREAD

**Issue by skody01** [Moe-Dahan/PC-AimAssist#1]
Exception has occurred: ImportError
cannot import name 'TryExcept' from 'utils' (C:\Users\Astar\AppData\Local\Programs\Python\Python311\Lib\site-packages\utils\__init__.py)
  File "C:\Users\Astar\.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 27, in <module>
    from utils import TryExcept
ImportError: cannot import name 'TryExcept' from 'utils' (C:\Users\Astar\AppData\Local\Programs\Python\Python311\Lib\site-packages\utils\__init__.py)

**Comment by Moe-Dahan** [comment]
pip install pywin32
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 (run python3.10 not python3.11)
pip install -qr https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt
pip install pyautogui
pip install opencv-python
pip install pydirectinput

should be good
